INSERT INTO core_rol VALUES (1,'Cliente');
INSERT INTO core_rol VALUES (2,'Vendedor');

INSERT INTO core_categoria VALUES (1, 'Herramientas');
INSERT INTO core_categoria VALUES (2, 'Tierra');
INSERT INTO core_categoria VALUES (3, 'Maceteros');
INSERT INTO core_categoria VALUES (4, 'Semillas');

INSERT INTO core_region VALUES (1, 'Arica y Parinacota');
INSERT INTO core_region VALUES (2, 'Tarapacá');
INSERT INTO core_region VALUES (3, 'Antofagasta');
INSERT INTO core_region VALUES (4, 'Atacama');
INSERT INTO core_region VALUES (5, 'Coquimbo');
INSERT INTO core_region VALUES (6, 'Valparaíso');
INSERT INTO core_region VALUES (7, 'Región del Libertador Gral. Bernardo O’Higgins');
INSERT INTO core_region VALUES (8, 'Región del Maule');
INSERT INTO core_region VALUES (9, 'Región de Ñuble');
INSERT INTO core_region VALUES (10, 'Región del Biobío');
INSERT INTO core_region VALUES (11, 'Región de la Araucanía');
INSERT INTO core_region VALUES (12, 'Región de Los Ríos');
INSERT INTO core_region VALUES (13, 'Región de Los Lagos');
INSERT INTO core_region VALUES (14, 'Región Aisén del Gral. Carlos Ibáñez del Campo');
INSERT INTO core_region VALUES (15, 'Región de Magallanes y de la Antártica Chilena');
INSERT INTO core_region VALUES (16, 'Región Metropolitana de Santiago');

-- Tabla core_comuna
INSERT INTO core_comuna VALUES (1, 'Arica', 5, 1);
INSERT INTO core_comuna VALUES (2, 'Camarones', 10, 1);
INSERT INTO core_comuna VALUES (3, 'Putre', 100, 1);
INSERT INTO core_comuna VALUES (4, 'General Lagos', 9000000, 1);

INSERT INTO core_comuna VALUES (5, 'Iquique', 2);
INSERT INTO core_comuna VALUES (6, 'Alto Hospicio', 2);
INSERT INTO core_comuna VALUES (7, 'Pozo Almonte', 2);
INSERT INTO core_comuna VALUES (8, 'Camiña', 2);
INSERT INTO core_comuna VALUES (9, 'Colchane', 2);
INSERT INTO core_comuna VALUES (10, 'Huara', 2);
INSERT INTO core_comuna VALUES (11, 'Pica', 2);

INSERT INTO core_comuna VALUES (12, 'Antofagasta', 3);
INSERT INTO core_comuna VALUES (13, 'Mejillones', 3);
INSERT INTO core_comuna VALUES (14, 'Sierra Gorda', 3);
INSERT INTO core_comuna VALUES (15, 'Taltal', 3);
INSERT INTO core_comuna VALUES (16, 'Calama', 3);
INSERT INTO core_comuna VALUES (17, 'Ollagüe', 3);
INSERT INTO core_comuna VALUES (18, 'San Pedro de Atacama', 3);
INSERT INTO core_comuna VALUES (19, 'Tocopilla', 3);
INSERT INTO core_comuna VALUES (20, 'María Elena', 3);

INSERT INTO core_comuna VALUES (21, 'Copiapó', 4);
INSERT INTO core_comuna VALUES (22, 'Caldera', 4);
INSERT INTO core_comuna VALUES (23, 'Tierra Amarilla', 4);
INSERT INTO core_comuna VALUES (24, 'Chañaral', 4);
INSERT INTO core_comuna VALUES (25, 'Diego de Almagro', 4);
INSERT INTO core_comuna VALUES (26, 'Vallenar', 4);
INSERT INTO core_comuna VALUES (27, 'Alto del Carmen', 4);
INSERT INTO core_comuna VALUES (28, 'Freirina', 4);
INSERT INTO core_comuna VALUES (29, 'Huasco', 4);

INSERT INTO core_comuna VALUES (30, 'La Serena', 5);
INSERT INTO core_comuna VALUES (31, 'Coquimbo', 5);
INSERT INTO core_comuna VALUES (32, 'Andacollo', 5);
INSERT INTO core_comuna VALUES (33, 'La Higuera', 5);
INSERT INTO core_comuna VALUES (34, 'Paiguano', 5);
INSERT INTO core_comuna VALUES (35, 'Vicuña', 5);
INSERT INTO core_comuna VALUES (36, 'Illapel', 5);
INSERT INTO core_comuna VALUES (37, 'Canela', 5);
INSERT INTO core_comuna VALUES (38, 'Los Vilos', 5);
INSERT INTO core_comuna VALUES (39, 'Salamanca', 5);
INSERT INTO core_comuna VALUES (40, 'Ovalle', 5);
INSERT INTO core_comuna VALUES (41, 'Combarbalá', 5);
INSERT INTO core_comuna VALUES (42, 'Monte Patria', 5);
INSERT INTO core_comuna VALUES (43, 'Punitaqui', 5);
INSERT INTO core_comuna VALUES (44, 'Río Hurtado', 5);

INSERT INTO core_comuna VALUES (45, 'Valparaíso', 6);
INSERT INTO core_comuna VALUES (46, 'Casablanca', 6);
INSERT INTO core_comuna VALUES (47, 'Concón', 6);
INSERT INTO core_comuna VALUES (48, 'Juan Fernández', 6);
INSERT INTO core_comuna VALUES (49, 'Puchuncaví', 6);
INSERT INTO core_comuna VALUES (50, 'Quintero', 6);
INSERT INTO core_comuna VALUES (51, 'Viña del Mar', 6);
INSERT INTO core_comuna VALUES (52, 'Isla de Pascua', 6);
INSERT INTO core_comuna VALUES (53, 'Los Andes', 6);
INSERT INTO core_comuna VALUES (54, 'Calle Larga', 6);
INSERT INTO core_comuna VALUES (55, 'Rinconada', 6);
INSERT INTO core_comuna VALUES (56, 'San Esteban', 6);
INSERT INTO core_comuna VALUES (57, 'La Ligua', 6);
INSERT INTO core_comuna VALUES (58, 'Cabildo', 6);
INSERT INTO core_comuna VALUES (59, 'Papudo', 6);
INSERT INTO core_comuna VALUES (60, 'Petorca', 6);
INSERT INTO core_comuna VALUES (61, 'Zapallar', 6);
INSERT INTO core_comuna VALUES (62, 'Quillota', 6);
INSERT INTO core_comuna VALUES (63, 'Calera', 6);
INSERT INTO core_comuna VALUES (64, 'Hijuelas', 6);
INSERT INTO core_comuna VALUES (65, 'La Cruz', 6);
INSERT INTO core_comuna VALUES (66, 'Nogales', 6);
INSERT INTO core_comuna VALUES (67, 'San Antonio', 6);
INSERT INTO core_comuna VALUES (68, 'Algarrobo', 6);
INSERT INTO core_comuna VALUES (69, 'Cartagena', 6);
INSERT INTO core_comuna VALUES (70, 'El Quisco', 6);
INSERT INTO core_comuna VALUES (71, 'El Tabo', 6);
INSERT INTO core_comuna VALUES (72, 'Santo Domingo', 6);
INSERT INTO core_comuna VALUES (73, 'San Felipe', 6);
INSERT INTO core_comuna VALUES (74, 'Catemu', 6);
INSERT INTO core_comuna VALUES (75, 'Llaillay', 6);
INSERT INTO core_comuna VALUES (76, 'Panquehue', 6);
INSERT INTO core_comuna VALUES (77, 'Putaendo', 6);
INSERT INTO core_comuna VALUES (78, 'Santa María', 6);
INSERT INTO core_comuna VALUES (79, 'Quilpué', 6);
INSERT INTO core_comuna VALUES (80, 'Limache', 6);
INSERT INTO core_comuna VALUES (81, 'Olmué', 6);
INSERT INTO core_comuna VALUES (82, 'Villa Alemana', 6);

INSERT INTO core_comuna VALUES (83, 'Rancagua', 7);
INSERT INTO core_comuna VALUES (84, 'Codegua', 7);
INSERT INTO core_comuna VALUES (85, 'Coinco', 7);
INSERT INTO core_comuna VALUES (86, 'Coltauco', 7);
INSERT INTO core_comuna VALUES (87, 'Doñihue', 7);
INSERT INTO core_comuna VALUES (88, 'Graneros', 7);
INSERT INTO core_comuna VALUES (89, 'Las Cabras', 7);
INSERT INTO core_comuna VALUES (90, 'Machalí', 7);
INSERT INTO core_comuna VALUES (91, 'Malloa', 7);
INSERT INTO core_comuna VALUES (92, 'Mostazal', 7);
INSERT INTO core_comuna VALUES (93, 'Olivar', 7);
INSERT INTO core_comuna VALUES (94, 'Peumo', 7);
INSERT INTO core_comuna VALUES (95, 'Pichidegua', 7);
INSERT INTO core_comuna VALUES (96, 'Quinta de Tilcoco', 7);
INSERT INTO core_comuna VALUES (97, 'Rengo', 7);
INSERT INTO core_comuna VALUES (98, 'Requínoa', 7);
INSERT INTO core_comuna VALUES (99, 'San Vicente', 7);
INSERT INTO core_comuna VALUES (100, 'Pichilemu', 7);
INSERT INTO core_comuna VALUES (101, 'La Estrella', 7);
INSERT INTO core_comuna VALUES (102, 'Litueche', 7);
INSERT INTO core_comuna VALUES (103, 'Marchihue', 7);
INSERT INTO core_comuna VALUES (104, 'Navidad', 7);
INSERT INTO core_comuna VALUES (105, 'Paredones', 7);
INSERT INTO core_comuna VALUES (106, 'San Fernando', 7);
INSERT INTO core_comuna VALUES (107, 'Chépica', 7);
INSERT INTO core_comuna VALUES (108, 'Chimbarongo', 7);
INSERT INTO core_comuna VALUES (109, 'Lolol', 7);
INSERT INTO core_comuna VALUES (110, 'Nancagua', 7);
INSERT INTO core_comuna VALUES (111, 'Palmilla', 7);
INSERT INTO core_comuna VALUES (112, 'Peralillo', 7);
INSERT INTO core_comuna VALUES (113, 'Placilla', 7);
INSERT INTO core_comuna VALUES (114, 'Pumanque', 7);
INSERT INTO core_comuna VALUES (115, 'Santa Cruz', 7);

INSERT INTO core_comuna VALUES (116, 'Talca', 8);
INSERT INTO core_comuna VALUES (117, 'Constitución', 8);
INSERT INTO core_comuna VALUES (118, 'Curepto', 8);
INSERT INTO core_comuna VALUES (119, 'Empedrado', 8);
INSERT INTO core_comuna VALUES (120, 'Maule', 8);
INSERT INTO core_comuna VALUES (121, 'Pelarco', 8);
INSERT INTO core_comuna VALUES (122, 'Pencahue', 8);
INSERT INTO core_comuna VALUES (123, 'Río Claro', 8);
INSERT INTO core_comuna VALUES (124, 'San Clemente', 8);
INSERT INTO core_comuna VALUES (125, 'San Rafael', 8);
INSERT INTO core_comuna VALUES (126, 'Cauquenes', 8);
INSERT INTO core_comuna VALUES (127, 'Chanco', 8);
INSERT INTO core_comuna VALUES (128, 'Pelluhue', 8);
INSERT INTO core_comuna VALUES (129, 'Curicó', 8);
INSERT INTO core_comuna VALUES (130, 'Hualañé', 8);
INSERT INTO core_comuna VALUES (131, 'Licantén', 8);
INSERT INTO core_comuna VALUES (132, 'Molina', 8);
INSERT INTO core_comuna VALUES (133, 'Rauco', 8);
INSERT INTO core_comuna VALUES (134, 'Romeral', 8);
INSERT INTO core_comuna VALUES (135, 'Sagrada Familia', 8);
INSERT INTO core_comuna VALUES (136, 'Teno', 8);
INSERT INTO core_comuna VALUES (137, 'Vichuquén', 8);
INSERT INTO core_comuna VALUES (138, 'Linares', 8);
INSERT INTO core_comuna VALUES (139, 'Colbún', 8);
INSERT INTO core_comuna VALUES (140, 'Longaví', 8);
INSERT INTO core_comuna VALUES (141, 'Parral', 8);
INSERT INTO core_comuna VALUES (142, 'Retiro', 8);
INSERT INTO core_comuna VALUES (143, 'San Javier', 8);
INSERT INTO core_comuna VALUES (144, 'Villa Alegre', 8);
INSERT INTO core_comuna VALUES (145, 'Yerbas Buenas', 8);

INSERT INTO core_comuna VALUES (146, 'Cobquecura', 9);
INSERT INTO core_comuna VALUES (147, 'Coelemu', 9);
INSERT INTO core_comuna VALUES (148, 'Ninhue', 9);
INSERT INTO core_comuna VALUES (149, 'Portezuelo', 9);
INSERT INTO core_comuna VALUES (150, 'Quirihue', 9);
INSERT INTO core_comuna VALUES (151, 'Ránquil', 9);
INSERT INTO core_comuna VALUES (152, 'Treguaco', 9);
INSERT INTO core_comuna VALUES (153, 'Bulnes', 9);
INSERT INTO core_comuna VALUES (154, 'Chillán Viejo', 9);
INSERT INTO core_comuna VALUES (155, 'Chillán', 9);
INSERT INTO core_comuna VALUES (156, 'El Carmen', 9);
INSERT INTO core_comuna VALUES (157, 'Pemuco', 9);
INSERT INTO core_comuna VALUES (158, 'Pinto', 9);
INSERT INTO core_comuna VALUES (159, 'Quillón', 9);
INSERT INTO core_comuna VALUES (160, 'San Ignacio', 9);
INSERT INTO core_comuna VALUES (161, 'Yungay', 9);
INSERT INTO core_comuna VALUES (162, 'Coihueco', 9);
INSERT INTO core_comuna VALUES (163, 'Ñiquén', 9);
INSERT INTO core_comuna VALUES (164, 'San Carlos', 9);
INSERT INTO core_comuna VALUES (165, 'San Fabián', 9);
INSERT INTO core_comuna VALUES (166, 'San Nicolás', 9);


INSERT INTO core_comuna VALUES (166, 'Concepción', 10);
INSERT INTO core_comuna VALUES (167, 'Coronel', 10);
INSERT INTO core_comuna VALUES (168, 'Chiguayante', 10);
INSERT INTO core_comuna VALUES (169, 'Florida', 10);
INSERT INTO core_comuna VALUES (170, 'Hualqui', 10);
INSERT INTO core_comuna VALUES (171, 'Lota', 10);
INSERT INTO core_comuna VALUES (172, 'Penco', 10);
INSERT INTO core_comuna VALUES (173, 'San Pedro de la Paz', 10);
INSERT INTO core_comuna VALUES (174, 'Santa Juana', 10);
INSERT INTO core_comuna VALUES (175, 'Talcahuano', 10);
INSERT INTO core_comuna VALUES (176, 'Tomé', 10);
INSERT INTO core_comuna VALUES (177, 'Hualpén', 10);
INSERT INTO core_comuna VALUES (178, 'Lebu', 10);
INSERT INTO core_comuna VALUES (179, 'Arauco', 10);
INSERT INTO core_comuna VALUES (180, 'Cañete', 10);
INSERT INTO core_comuna VALUES (181, 'Contulmo', 10);
INSERT INTO core_comuna VALUES (182, 'Curanilahue', 10);
INSERT INTO core_comuna VALUES (183, 'Los �?lamos', 10);
INSERT INTO core_comuna VALUES (184, 'Tirúa', 10);
INSERT INTO core_comuna VALUES (185, 'Los �?ngeles', 10);
INSERT INTO core_comuna VALUES (186, 'Antuco', 10);
INSERT INTO core_comuna VALUES (187, 'Cabrero', 10);
INSERT INTO core_comuna VALUES (188, 'Laja', 10);
INSERT INTO core_comuna VALUES (189, 'Mulchén', 10);
INSERT INTO core_comuna VALUES (190, 'Nacimiento', 10);
INSERT INTO core_comuna VALUES (191, 'Negrete', 10);
INSERT INTO core_comuna VALUES (192, 'Quilaco', 10);
INSERT INTO core_comuna VALUES (193, 'Quilleco', 10);
INSERT INTO core_comuna VALUES (194, 'San Rosendo', 10);
INSERT INTO core_comuna VALUES (195, 'Santa Bárbara', 10);
INSERT INTO core_comuna VALUES (196, 'Tucapel', 10);
INSERT INTO core_comuna VALUES (197, 'Yumbel', 10);
INSERT INTO core_comuna VALUES (198, 'Alto Biobío', 10);

INSERT INTO core_comuna VALUES (199, 'Temuco', 11);
INSERT INTO core_comuna VALUES (200, 'Carahue', 11);
INSERT INTO core_comuna VALUES (201, 'Cunco', 11);
INSERT INTO core_comuna VALUES (202, 'Curarrehue', 11);
INSERT INTO core_comuna VALUES (203, 'Freire', 11);
INSERT INTO core_comuna VALUES (204, 'Galvarino', 11);
INSERT INTO core_comuna VALUES (205, 'Gorbea', 11);
INSERT INTO core_comuna VALUES (206, 'Lautaro', 11);
INSERT INTO core_comuna VALUES (207, 'Loncoche', 11);
INSERT INTO core_comuna VALUES (208, 'Melipeuco', 11);
INSERT INTO core_comuna VALUES (209, 'Nueva Imperial', 11);
INSERT INTO core_comuna VALUES (210, 'Padre las Casas', 11);
INSERT INTO core_comuna VALUES (211, 'Perquenco', 11);
INSERT INTO core_comuna VALUES (212, 'Pitrufquén', 11);
INSERT INTO core_comuna VALUES (213, 'Pucón', 11);
INSERT INTO core_comuna VALUES (214, 'Saavedra', 11);
INSERT INTO core_comuna VALUES (215, 'Teodoro Schmidt', 11);
INSERT INTO core_comuna VALUES (216, 'Toltén', 11);
INSERT INTO core_comuna VALUES (217, 'Vilcún', 11);
INSERT INTO core_comuna VALUES (218, 'Villarrica', 11);
INSERT INTO core_comuna VALUES (219, 'Cholchol', 11);
INSERT INTO core_comuna VALUES (220, 'Angol', 11);
INSERT INTO core_comuna VALUES (221, 'Collipulli', 11);
INSERT INTO core_comuna VALUES (222, 'Curacautín', 11);
INSERT INTO core_comuna VALUES (223, 'Ercilla', 11);
INSERT INTO core_comuna VALUES (224, 'Lonquimay', 11);
INSERT INTO core_comuna VALUES (225, 'Los Sauces', 11);
INSERT INTO core_comuna VALUES (226, 'Lumaco', 11);
INSERT INTO core_comuna VALUES (227, 'Purén', 11);
INSERT INTO core_comuna VALUES (228, 'Renaico', 11);
INSERT INTO core_comuna VALUES (229, 'Traiguén', 11);
INSERT INTO core_comuna VALUES (230, 'Victoria', 11);

INSERT INTO core_comuna VALUES (231, 'Valdivia', 12);
INSERT INTO core_comuna VALUES (232, 'Corral', 12);
INSERT INTO core_comuna VALUES (233, 'Lanco', 12);
INSERT INTO core_comuna VALUES (234, 'Los Lagos', 12);
INSERT INTO core_comuna VALUES (235, 'Máfil', 12);
INSERT INTO core_comuna VALUES (236, 'Mariquina', 12);
INSERT INTO core_comuna VALUES (237, 'Paillaco', 12);
INSERT INTO core_comuna VALUES (238, 'Panguipulli', 12);
INSERT INTO core_comuna VALUES (239, 'La Unión', 12);
INSERT INTO core_comuna VALUES (240, 'Futrono', 12);
INSERT INTO core_comuna VALUES (241, 'Lago Ranco', 12);
INSERT INTO core_comuna VALUES (242, 'Río Bueno', 12);

INSERT INTO core_comuna VALUES (251, 'Puerto Montt', 13);
INSERT INTO core_comuna VALUES (252, 'Calbuco', 13);
INSERT INTO core_comuna VALUES (253, 'Cochamó', 13);
INSERT INTO core_comuna VALUES (254, 'Fresia', 13);
INSERT INTO core_comuna VALUES (255, 'Frutillar', 13);
INSERT INTO core_comuna VALUES (256, 'Los Muermos', 13);
INSERT INTO core_comuna VALUES (257, 'Llanquihue', 13);
INSERT INTO core_comuna VALUES (258, 'Maullín', 13);
INSERT INTO core_comuna VALUES (259, 'Puerto Varas', 13);
INSERT INTO core_comuna VALUES (260, 'Castro', 13);
INSERT INTO core_comuna VALUES (261, 'Ancud', 13);
INSERT INTO core_comuna VALUES (262, 'Chonchi', 13);
INSERT INTO core_comuna VALUES (263, 'Curaco de Vélez', 13);
INSERT INTO core_comuna VALUES (264, 'Dalcahue', 13);
INSERT INTO core_comuna VALUES (265, 'Puqueldón', 13);
INSERT INTO core_comuna VALUES (266, 'Queilén', 13);
INSERT INTO core_comuna VALUES (267, 'Quellón', 13);
INSERT INTO core_comuna VALUES (268, 'Quemchi', 13);
INSERT INTO core_comuna VALUES (269, 'Quinchao', 13);
INSERT INTO core_comuna VALUES (270, 'Osorno', 13);
INSERT INTO core_comuna VALUES (271, 'Puerto Octay', 13);
INSERT INTO core_comuna VALUES (272, 'Purranque', 13);
INSERT INTO core_comuna VALUES (273, 'Puyehue', 13);
INSERT INTO core_comuna VALUES (274, 'Río Negro', 13);
INSERT INTO core_comuna VALUES (275, 'San Juan de la Costa', 13);
INSERT INTO core_comuna VALUES (276, 'San Pablo', 13);
INSERT INTO core_comuna VALUES (277, 'Chaitén', 13);
INSERT INTO core_comuna VALUES (278, 'Futaleufú', 13);
INSERT INTO core_comuna VALUES (279, 'Hualaihué', 13);
INSERT INTO core_comuna VALUES (280, 'Palena', 13);

INSERT INTO core_comuna VALUES (281, 'Coyhaique', 14);
INSERT INTO core_comuna VALUES (282, 'Lago Verde', 14);
INSERT INTO core_comuna VALUES (283, 'Aysén', 14);
INSERT INTO core_comuna VALUES (284, 'Cisnes', 14);
INSERT INTO core_comuna VALUES (285, 'Guaitecas', 14);
INSERT INTO core_comuna VALUES (286, 'Cochrane', 14);
INSERT INTO core_comuna VALUES (287, 'O Higgins', 14);
INSERT INTO core_comuna VALUES (288, 'Tortel', 14);
INSERT INTO core_comuna VALUES (289, 'Chile Chico', 14);
INSERT INTO core_comuna VALUES (290, 'Río Ibáñez', 14);

INSERT INTO core_comuna VALUES (291, 'Punta Arenas', 15);
INSERT INTO core_comuna VALUES (292, 'Laguna Blanca', 15);
INSERT INTO core_comuna VALUES (293, 'Río Verde', 15);
INSERT INTO core_comuna VALUES (294, 'San Gregorio', 15);
INSERT INTO core_comuna VALUES (295, 'Cabo de Hornos', 15);
INSERT INTO core_comuna VALUES (296, 'Antártica', 15);
INSERT INTO core_comuna VALUES (297, 'Porvenir', 15);
INSERT INTO core_comuna VALUES (298, 'Primavera', 15);
INSERT INTO core_comuna VALUES (299, 'Timaukel', 15);
INSERT INTO core_comuna VALUES (300, 'Natales', 15);
INSERT INTO core_comuna VALUES (301, 'Torres del Paine', 15);

INSERT INTO core_comuna VALUES (302, 'Cerrillos', 16);
INSERT INTO core_comuna VALUES (303, 'Cerro Navia', 16);
INSERT INTO core_comuna VALUES (304, 'Conchalí', 16);
INSERT INTO core_comuna VALUES (305, 'El Bosque', 16);
INSERT INTO core_comuna VALUES (306, 'Estación Central', 16);
INSERT INTO core_comuna VALUES (307, 'Huechuraba', 16);
INSERT INTO core_comuna VALUES (308, 'Independencia', 16);
INSERT INTO core_comuna VALUES (309, 'La Cisterna', 16);
INSERT INTO core_comuna VALUES (310, 'La Florida', 16);
INSERT INTO core_comuna VALUES (311, 'La Granja', 16);
INSERT INTO core_comuna VALUES (312, 'La Pintana', 16);
INSERT INTO core_comuna VALUES (313, 'La Reina', 16);
INSERT INTO core_comuna VALUES (314, 'Las Condes', 16);
INSERT INTO core_comuna VALUES (315, 'Lo Barnechea', 16);
INSERT INTO core_comuna VALUES (316, 'Lo Espejo', 16);
INSERT INTO core_comuna VALUES (317, 'Lo Prado', 16);
INSERT INTO core_comuna VALUES (318, 'Macul', 16);
INSERT INTO core_comuna VALUES (319, 'Maipú', 16);
INSERT INTO core_comuna VALUES (320, 'Ñuñoa', 16);
INSERT INTO core_comuna VALUES (321, 'Pedro Aguirre Cerda', 16);
INSERT INTO core_comuna VALUES (322, 'Peñalolén', 16);
INSERT INTO core_comuna VALUES (323, 'Providencia', 16);
INSERT INTO core_comuna VALUES (324, 'Pudahuel', 16);
INSERT INTO core_comuna VALUES (325, 'Quilicura', 16);
INSERT INTO core_comuna VALUES (326, 'Quinta Normal', 16);
INSERT INTO core_comuna VALUES (327, 'Recoleta', 16);
INSERT INTO core_comuna VALUES (328, 'Renca', 16);
INSERT INTO core_comuna VALUES (329, 'Santiago', 16);
INSERT INTO core_comuna VALUES (330, 'San Joaquín', 16);
INSERT INTO core_comuna VALUES (331, 'San Miguel', 16);
INSERT INTO core_comuna VALUES (332, 'San Ramón', 16);
INSERT INTO core_comuna VALUES (333, 'Vitacura', 16);
INSERT INTO core_comuna VALUES (334, 'Puente Alto', 16);
INSERT INTO core_comuna VALUES (335, 'Pirque', 16);
INSERT INTO core_comuna VALUES (336, 'San José de Maipo', 16);
INSERT INTO core_comuna VALUES (337, 'Colina', 16);
INSERT INTO core_comuna VALUES (338, 'Lampa', 16);
INSERT INTO core_comuna VALUES (339, 'Tiltil', 16);
INSERT INTO core_comuna VALUES (340, 'San Bernardo', 16);
INSERT INTO core_comuna VALUES (341, 'Buin', 16);
INSERT INTO core_comuna VALUES (342, 'Calera de Tango', 16);
INSERT INTO core_comuna VALUES (343, 'Paine', 16);
INSERT INTO core_comuna VALUES (344, 'Melipilla', 16);
INSERT INTO core_comuna VALUES (345, 'Alhué', 16);
INSERT INTO core_comuna VALUES (346, 'Curacaví', 16);
INSERT INTO core_comuna VALUES (347, 'María Pinto', 16);
INSERT INTO core_comuna VALUES (348, 'San Pedro', 16);
INSERT INTO core_comuna VALUES (349, 'Talagante', 16);
INSERT INTO core_comuna VALUES (350, 'El Monte', 16);
INSERT INTO core_comuna VALUES (351, 'Isla de Maipo', 16);
INSERT INTO core_comuna VALUES (352, 'Padre Hurtado', 16);
INSERT INTO core_comuna VALUES (353, 'Peñaflor', 16);

