INSERT INTO core_rol VALUES (1,'Cliente');
INSERT INTO core_rol VALUES (2,'Vendedor');

INSERT INTO core_categoria VALUES (1, 'Herramientas');
INSERT INTO core_categoria VALUES (2, 'Tierra');
INSERT INTO core_categoria VALUES (3, 'Maceteros');
INSERT INTO core_categoria VALUES (4, 'Semillas');

INSERT INTO core_comuna VALUES (1, 'Cerrillos', 2000);
INSERT INTO core_comuna VALUES (2, 'Cerro Navia', 1500);
INSERT INTO core_comuna VALUES (3, 'Conchalí', 1000);
INSERT INTO core_comuna VALUES (4, 'El Bosque', 2500);
INSERT INTO core_comuna VALUES (5, 'Estación Central', 1500);
INSERT INTO core_comuna VALUES (6, 'Huechuraba', 2000);
INSERT INTO core_comuna VALUES (7, 'Independencia', 1000);
INSERT INTO core_comuna VALUES (8, 'La Cisterna', 2500);
INSERT INTO core_comuna VALUES (9, 'La Florida', 2000);
INSERT INTO core_comuna VALUES (10, 'La Granja', 2500);
INSERT INTO core_comuna VALUES (11, 'La Pintana', 3000);
INSERT INTO core_comuna VALUES (12, 'La Reina', 1500);
INSERT INTO core_comuna VALUES (13, 'Las Condes', 1000);
INSERT INTO core_comuna VALUES (14, 'Lo Barnechea', 1500);
INSERT INTO core_comuna VALUES (15, 'Lo Espejo', 2500);
INSERT INTO core_comuna VALUES (16, 'Lo Prado', 2000);
INSERT INTO core_comuna VALUES (17, 'Macul', 1000);
INSERT INTO core_comuna VALUES (18, 'Maipú', 2000);
INSERT INTO core_comuna VALUES (19, 'Ñuñoa', 1000);
INSERT INTO core_comuna VALUES (20, 'Pedro Aguirre Cerda', 2500);
INSERT INTO core_comuna VALUES (21, 'Peñalolén', 1500);
INSERT INTO core_comuna VALUES (22, 'Providencia', 1000);
INSERT INTO core_comuna VALUES (23, 'Pudahuel', 2000);
INSERT INTO core_comuna VALUES (24, 'Quilicura', 2000);
INSERT INTO core_comuna VALUES (25, 'Quinta Normal', 2000);
INSERT INTO core_comuna VALUES (26, 'Recoleta', 1000);
INSERT INTO core_comuna VALUES (27, 'Renca', 2000);
INSERT INTO core_comuna VALUES (28, 'Santiago', 1000);
INSERT INTO core_comuna VALUES (29, 'San Joaquín', 1500);
INSERT INTO core_comuna VALUES (30, 'San Miguel', 1500);
INSERT INTO core_comuna VALUES (31, 'San Ramón', 2500);
INSERT INTO core_comuna VALUES (32, 'Vitacura', 1000);
INSERT INTO core_comuna VALUES (33, 'Puente Alto', 3000);
INSERT INTO core_comuna VALUES (34, 'Pirque', 3500);
INSERT INTO core_comuna VALUES (35, 'San José de Maipo', 3500);
INSERT INTO core_comuna VALUES (36, 'Colina', 3000);
INSERT INTO core_comuna VALUES (37, 'Lampa', 3500);
INSERT INTO core_comuna VALUES (38, 'Tiltil', 3500);
INSERT INTO core_comuna VALUES (39, 'San Bernardo', 2500);
INSERT INTO core_comuna VALUES (40, 'Buin', 2500);
INSERT INTO core_comuna VALUES (41, 'Calera de Tango', 2500);
INSERT INTO core_comuna VALUES (42, 'Paine', 3000);
INSERT INTO core_comuna VALUES (43, 'Melipilla', 3000);
INSERT INTO core_comuna VALUES (44, 'Alhué', 3500);
INSERT INTO core_comuna VALUES (45, 'Curacaví', 3500);
INSERT INTO core_comuna VALUES (46, 'María Pinto', 3500);
INSERT INTO core_comuna VALUES (47, 'San Pedro', 3500);
INSERT INTO core_comuna VALUES (48, 'Talagante', 2500);
INSERT INTO core_comuna VALUES (49, 'El Monte', 3000);
INSERT INTO core_comuna VALUES (50, 'Isla de Maipo', 3000);
INSERT INTO core_comuna VALUES (51, 'Padre Hurtado', 3000);
INSERT INTO core_comuna VALUES (52, 'Peñaflor', 3000);
INSERT INTO core_comuna VALUES (99, '', 0);
commit;


