# Generated by Django 4.1.5 on 2023-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='com_nom',
            field=models.CharField(max_length=25, verbose_name='Nombre de Comuna'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='dir_calle',
            field=models.CharField(max_length=25, verbose_name='Nombre de Calle'),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_nom',
            field=models.CharField(max_length=25, verbose_name='Nombre de Region'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_correo',
            field=models.CharField(max_length=35, verbose_name='Correo de Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_rut',
            field=models.CharField(max_length=9, verbose_name='Rut de Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_telefono',
            field=models.CharField(max_length=12, verbose_name='Telefono de Usuario'),
        ),
    ]
