# Generated by Django 4.2.1 on 2023-06-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
