# Generated by Django 4.2.1 on 2023-06-23 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la pregunta')),
                ('pregunta', models.CharField(max_length=100, verbose_name='Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Respuesta')),
                ('respuesta', models.CharField(max_length=100, verbose_name='Respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Historial')),
                ('nom_prod', models.CharField(max_length=50, verbose_name='Nombre de Producto')),
                ('img_prod', models.ImageField(upload_to='', verbose_name='Foto de Producto')),
                ('cant_prod', models.IntegerField(verbose_name='Foto de Producto')),
                ('precio_prod', models.IntegerField(verbose_name='Precio del producto')),
                ('subtotal_prod', models.IntegerField(verbose_name='Subtotal')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compra')),
            ],
        ),
    ]
