# Generated by Django 4.2.1 on 2023-06-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prod_nom',
            field=models.CharField(max_length=120, verbose_name='Nombre de Producto'),
        ),
    ]
