# Generated by Django 4.2.1 on 2023-05-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='us_rut',
            field=models.CharField(max_length=12, verbose_name='Rut de Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_telefono',
            field=models.CharField(max_length=15, verbose_name='Telefono de Usuario'),
        ),
    ]
