# Generated by Django 4.2.1 on 2023-06-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='respuesta',
            new_name='respuesta_pred',
        ),
    ]
