# Generated by Django 4.2.1 on 2023-05-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_us_rut_alter_usuario_us_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tajeta',
            new_name='tarjeta',
        ),
    ]
