# Generated by Django 4.2.1 on 2023-06-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_prod_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cop_carrito',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cop_fech_desp',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='estado',
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id_detalle',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Detalle'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
