# Generated by Django 4.2.1 on 2023-06-24 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_respuesta_respuesta_respuesta_pred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='id_pregunta',
            new_name='id_respuesta',
        ),
    ]
