# Generated by Django 4.2.1 on 2023-06-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_direccion_dir_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='com_cost_envio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
