# Generated by Django 4.2.1 on 2023-06-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_compra_cop_carrito_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='id_region',
            new_name='id_com',
        ),
    ]
