# Generated by Django 4.2.1 on 2023-06-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_id_region_comuna_id_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='com_nom',
            field=models.CharField(max_length=50, verbose_name='Nombre de Comuna'),
        ),
    ]
