# Generated by Django 4.2.1 on 2023-06-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comuna_com_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='dir_calle',
            field=models.CharField(max_length=50, verbose_name='Nombre de Calle'),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_nom',
            field=models.CharField(max_length=50, verbose_name='Nombre de Region'),
        ),
    ]
